disabled_rules:
  - opening_brace
  - todo
  - notification_center_detachment
  - block_based_kvo
  - identifier_name

opt_in_rules:
  - anyobject_protocol
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - explicit_self
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - modifier_order
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - untyped_error_in_catch
  - unneeded_parentheses_in_closure_argument
  - unused_declaration
  - unused_import
  - vertical_whitespace_between_cases
  - yoda_condition

excluded:
  - Pods
  - "*/Pods"
  - R.generated.swift
  - .build

# We exclude function (which is present by default)
implicit_return:
  included:
    - closure
    - getter

private_over_fileprivate:
  validate_extensions: true
  severity: error

force_unwrapping:
  severity: error

redundant_type_annotation: error

type_name:
  min_length: 3
  max_length:
    warning: 60
    error: 60
  excluded:
    - Id

identifier_name:
  allowed_symbols: "_"
  min_length: 3
  max_length:
    warning: 60
    error: 60
  excluded:
    - id
    - x
    - y

line_length:
  warning: 120
  error: 120
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 300
  error: 300

function_parameter_count:
  warning: 8
  error: 8

type_body_length:
  warning: 350
  error: 450

file_length:
  warning: 1000
  error: 1000
  ignore_comment_only_lines: true

enum_case_associated_values_count:
  warning: 3
  error: 3

reporter: "xcode"
